services:
  mariadb-test:
    image: mariadb:10.6
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: share_trip_db
      MARIADB_USER: mariadb
      MARIADB_PASSWORD: mariadb
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - mariadb-test-data:/var/lib/mysql

volumes:
  mariadb-test-data:
