services:
  - type: web
    name: cung-tuyen-api
    runtime: node
    plan: free
    buildCommand: yarn install --frozen-lockfile && yarn build && yarn db:migrate:dist && yarn db:seed:dist
    startCommand: node dist/index.js
    envVars:
      - key: ZALO_APP_ID
        sync: false
      - key: ZALO_APP_SECRET
        sync: false
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: cung-tuyen-db
          property: connectionString
    healthCheckPath: /health

databases:
  - name: cung-tuyen-db
    databaseName: cung_tuyen
    user: cung_tuyen
    plan: free
