services:
  - type: web
    name: cung-tuyen-api
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm run db:schema && npm run db:seed && npm start
    envVars:
      - key: ZALO_APP_ID
        sync: false
      - key: ZALO_APP_SECRET
        sync: false
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
    healthCheckPath: /health
